### ISSUE TITLE
Fix data recording for BCY | Spells of Genesis

### ISSUE THREAD

**Issue by vitalylvov** [cyberFund/api.cyber.fund#11]
данные toml:

```
system = "Spells of Genesis"
aliases.coinmarketcap = "Bitcrystals"
token.token_symbol = "BCY"
```

данные СМС:

```
"name":"Bitcrystals"
"symbol":"BCY"
```

в итоге данные не пишуться

**Comment by ghost** [comment]
there s no BCY/Bitcrystals/Spells.. at elasticsearch

**Comment by vitalylvov** [comment]
Ну так в том то и дело. Система есть у нас, есть у СМС, а в эластик не пишется. Что делать?
