### ISSUE TITLE
Add ignore for data recording for the systems that included in Chaingear ignorelist

### ISSUE THREAD

**Issue by vitalylvov** [cyberFund/api.cyber.fund#14]
Добавил файл в котором указаны системы по которым не нужно писать данные в индекс: `chaingear/ignorelist.txt`. 
Нужно придумать как игнорировать запись данных по ним

**Comment by mastercyb** [comment]
Я так понимаю, что сейчас они и так не пишутся, если под систему ничего нет.
Поэтому сейчас вроде как ничего добавлять не надо.  @tomarcafe, Верно? Я так понимаю, что этот игнор лист будет нужен нам для того, чтобы понимать какие системы появились новые.

**Comment by ghost** [comment]
немного не понял. то есть, появляется еще некий список, по которому мы данные не хотим вообще? или не хотим их через коинмаркеткап?

**Comment by mastercyb** [comment]
Сейчас у нас есть вайт-лист под названием Chaingear. Другого нет. Вет просто недогонял это когда создавал Issue. Blacklist мы сделали для того, чтобы:
1) удобно было бахнуть то, что есть
2) понимать, что появилось нового на CMC боль менее автоматизировано. Но это другая задача

**Comment by ghost** [comment]
ну собственно я лишние системы грохал уже именно через чг - чего не было все снес
