### ISSUE TITLE
Fix BTC trade volumes on 17.07.2015

### ISSUE THREAD

**Issue by vitalylvov** [cyberFund/api.cyber.fund#15]
Необходимо поменять `volume24_btc` в следующих документах:
AU6YxwVFVRXLQ4acPuzO
AU6Yy5eyVRXLQ4acPu64
AU6Y0C79VRXLQ4acPvCi
AU6Y4n2tVRXLQ4acPvhK
AU6Y66WmVRXLQ4acPvwe
AU6Y_fcLVRXLQ4acPwPq
AU6ZBx6OVRXLQ4acPwfQ
AU6ZIpidVRXLQ4acPxOC
AU6ZK8JTVRXLQ4acPxdo
AU6ZNOmMVRXLQ4acPxtO
AU8YGGEJoI0Q7apJwto7
AU6ZdQIHVRXLQ4acPzaY
AU6ZeZbqVRXLQ4acPziL
AU6ZwtnlVRXLQ4acP1e7
AU6Z0JX9VRXLQ4acP12U
AU6Z2b7fVRXLQ4acP2F6
AU6Z7BBLVRXLQ4acP2lG
AU6Z8KM4VRXLQ4acP2s5
AU6aDB4TVRXLQ4acP3br
AU6aHm15VRXLQ4acP363
AU6aIwKbVRXLQ4acP4Cq
AU6aJ5X6VRXLQ4acP4Kd
AU6aQxAZVRXLQ4acP45P
AU6agytXVRXLQ4acP6mZ
AU6ah8B6VRXLQ4acP6uM
AU6ajFQHVRXLQ4acP61_

на `177381`

**Comment by ghost** [comment]
не понимаю.

**Comment by vitalylvov** [comment]
Если посмотреть на график объемов торгов Биткоина, то можно увидеть что 17 июля были какие-то аномальные объемы. Ты уже подобную операцию проделывал, или я что-то путаю и мы тогда доки удаляли. В любом случае в документах по списку нужно бы поменять значения в поле `volume24_btc` на 177381

**Comment by ghost** [comment]
а, то есть у тебя id по еластику приведены?
их только удалить можно оттудова.

**Comment by ghost** [comment]
и лучше прям взять и удалить уже

**Comment by vitalylvov** [comment]
Да это ID документов в Эластике. Тогда давай удалять. Надеюсь что они никаким магическим образом не появятся снова

**Comment by ghost** [comment]
как их удалять? :)

2015-11-09 3:08 GMT+06:00 Vitaly notifications@github.com:

**Comment by vitalylvov** [comment]
@tomarcafe Интересное кино ))) А как ты в прошлый раз удалял? Вроде починили один раз https://github.com/cyberFund/api.cyber.fund/issues/4

**Comment by ghost** [comment]
а я не на еластике удалял, а в монге. но раз уж ты разжился айдишниками - может и грохнешь их заодно?

**Comment by ghost** [comment]
потому что менять документы не получится

**Comment by vitalylvov** [comment]
))) я ИДишники посмотрел через Кибану, а там возможности удалять доки нет

**Comment by ghost** [comment]
ок грохнул
