### ISSUE TITLE
Calculate supply from chaingear if cmc supply = 0

### ISSUE THREAD

**Issue by mastercyb** [cyberFund/api.cyber.fund#6]

**Comment by ghost** [comment]
please remind a case coin..

**Comment by mastercyb** [comment]
BitShares Music

**Comment by mastercyb** [comment]
One more case: [Sia](https://cyber.fund/system/Sia)

**Comment by ghost** [comment]
check again, shd work at least for dev

**Comment by mastercyb** [comment]
Я не понимаю как оно работат.
http://dev.cyber.fund/system/BitShares_Music
Умножаем одно на другое - никак не получается.

Давай я попробую объяснить на пальцах какие кейсы у нас бывают, и каким образом мы их обрабатываем:
1. На CMC есть цена, но нет суплая. Тогда нам суплай надо взять из Chaingear.
2. На CMC нет ни цены, ни суплая. Тогда нам надо взять из Chaingear и то и другое.
3. На CMC есть суплай, но нет цены. Уникальный кейс. Но давай и его предусмотрим. 

Получается, чтобы нам решить эту временную проблему, когда у ключего поставщика данных чего-то нет, нам нужно иметь возможность заткнуть эту дырку:
1. Либо статическими цифрами из Chaingear
2. Либо динамической обработкой как мы это делаем с Ethereum

В итоге получается, что данные надо брать следующим приортитетом:
1. Статика из Chaingear
2. Кастомные источники
3. CMC

Вот эта вся моя логика работает если, капитализация у нас сейчас рассчитывается перед тем как положиться в инедкс. Это же так?

**Comment by ghost** [comment]
нет не так. в индекс кладется тупо что есть.
расчеты делаем на стороне сайта.

2015-09-08 20:18 GMT+03:00 Dima Starodubcev notifications@github.com:

**Comment by mastercyb** [comment]
Хуево.

**Comment by mastercyb** [comment]
Давай созвонимся и решим как быть с этим

**Comment by mastercyb** [comment]
token.supplyFrom = “chaingear”
